use_frameworks!

target 'WJFastScrollViewPoint_Example' do
  pod 'WJFastScrollViewPoint', :path => '../'

  target 'WJFastScrollViewPoint_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
